version: '2'

services:
  nginx:
    build:
      context: ./
    image: halosan/filebeat-nginx:latest
    volumes:
      - nginx-logs:/var/log/nginx
    ports:
      - "8008:80"
    networks:
      - elk
    container_name: filebeat_nginx

  filebeat:
    image: docker.elastic.co/beats/filebeat:5.6.9
    volumes:
      - ./config/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - nginx-logs:/mnt/log
      - ./config/entrypoint.sh:/usr/share/filebeat/entrypoint.sh
    networks:
      - elk
    command: bash -c entrypoint.sh
    container_name: filebeat_filebeat

networks:
  elk:
    external:
      name: docker-elk_elk

volumes:
  nginx-logs:

