version: '2'

services:

  elasticsearch:
    build:
      context: elasticsearch/
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - elastic-search:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      ELASTIC_PASSWORD: changeme
    networks:
      - elk

  logstash:
    build:
      context: logstash/
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    ports:
      - "5000:5000"
      - "5044:5044" # Elastic beats port
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
    depends_on:
      - elasticsearch

  kibana:
    build:
      context: kibana/
    volumes:
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch

  # filebeat:
  #   image: docker.elastic.co/beats/filebeat:5.6.9
  #   volumes:
  #     - ./filebeat/config/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
  #     - nginx-logs:/mnt/log
  #     - ./filebeat/config/entrypoint.sh:/usr/share/filebeat/entrypoint.sh
  #   networks:
  #     - elk
  #   depends_on:
  #     - logstash
  #     - nginx
  #     - elasticsearch
  #     - kibana
  #   command: bash -c entrypoint.sh

  # nginx:
  #   image: nginx:1.13
  #   volumes:
  #     - nginx-logs:/var/log/nginx
  #   ports:
  #     - "8008:80"
  #   networks:
  #     - elk

networks:
  elk:
    driver: bridge

volumes:
  # nginx-logs:
  elastic-search:
    external: true

